import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./common/aside";
import Header from "./common/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} bg-[#131314]`}>
				<main className="flex">
					<Sidebar />
					<div className="flex-1">
						<Header />
						{children}
					</div>
				</main>
			</body>
		</html>
	);
}
